osx_image: xcode7
language: objective-c
sudo: false

script: xctool -scheme ScreamShot build

before_deploy:
- mkdir ScreamShot.app/
- cp -R $HOME/Library/Developer/Xcode/DerivedData/*/Build/Products/Debug/ScreamShot.app/ ScreamShot.app/
- zip -r ScreamShot.app.zip ./ScreamShot.app/

deploy:
  provider: releases
  api_key:
    secure: adMN6jAOVLxhc/k2vMoa6Lezju9/VFarNKVSkKPsmTLX6VOLCJ5fmBnbwAyonf5JHMmMJiCFb5+GE5stFli5Xc/fcH722MWe0ph5Fw8OhepJISUwKx/W3Qw7pL1aC446mEiCy71yqRMnLwGCoCDhZ1sBX75SfhGgHkdsbfm7m9yZf1V5GGrwWLoZZhFFwPHRk7VAXPMAXSG5ieecj9KtW7mwUlDgx9xJ/Jo4AptKh9rBouM0TDCYSCI2WtXNMiWDN2p2dj1PRUM40IDCwmuEO57Vh0ctoPyMDXt5LobxJeYcyxLxO6VGbCnf6t4JhKUaR8tQH+wf0HHcMql0i6mW+wq9HxACFRsKpuEd3RtEjmyPaVnoZHulsXDPZyzYTvs1Y+5oci50SqZkDSsUJE1QVguc6uAPADaFQKVsDXMaqHceqlIbBYUmINRpFTJcWyJ0gJynvSpn4hLLULjs88nTIylcsw4zr90Pfep+jta8nnzuKLpyZsUbOYIiDTTVyQvy6ct6wFWXrJ0GsE3Cyd/dkFfvpdAmt8EOkh11q2mUy/NzC+5o7G+HBuKMRebG5TlHvMXbysPZGiuDOAtmRGqkSrUkN45J9WY55lgTVYfe+nGpa7s3JXzr6zns45FSD8CdWLZMW5K3wh6X4UB4ChGrNxEb62O2+eSHGfibS0N21fo=
  file: ScreamShot.app.zip
  skip_cleanup: true
  on:
    repo: ScreamShot/ScreamShot
