language: objective-c
script: xctool -project mac2imgur.xcodeproj -scheme mac2imgur build
sudo: false
after_success:
  - "zip -r ScreamShot.app.zip $HOME/Library/Developer/Xcode/DerivedData/mac2imgur-*/Build/Products/Debug/ScreamShot.app/"
  - "curl -F \"image=@ScreamShot.app.zip;filename=ScreamShot.app.zip\" $UPLOAD_URL"