osx_image: xcode7
language: objective-c
sudo: false
script: xctool -scheme ScreamShot build
before_deploy:
- mkdir ScreamShot.app/
- cp -R $HOME/Library/Developer/Xcode/DerivedData/*/Build/Products/Debug/ScreamShot.app/
  ScreamShot.app/
- zip -r ScreamShot.app.zip ./ScreamShot.app/
deploy:
  provider: releases
  password:
    secure: yIh9KeppmPcv9o2eXLuMk4PjCuQc2NCWuGta4EiE57e+fSeX7PF1VFGgh7XAh9zMh/iy+s5n/IsP/6u+oaeD0Gjb9bwmmzkcSPq5ku33O9sVinDc1EW7IxHDY6SUPJZ5eIT2noGtSP7PDzwV5MHiqWrfQBhfpZtzdqNy051kwhnNF7dCA2hfH86WgQ6fN8vUH8EFdlkAmsxTNRwSgb83ajmbAhVeiAGhTEoxpMlSBWVU2V5BdtqcsShyKsy2Bf6w0EqKMTi27ZsyRiULn+IRgccU7+dXkqEXavSYGMDbrFkGArUSpd2dvTBXJeZ2B2NiDB/BSpJrOZo7Dn4Fvh0NlDfLUaIzpTX3yK+FHOvCnXovYtKSH7m7euDMPDnwznaPq3xqpinOBMcYBT90bTIGmG7fTADQfejP17jtsHLj5nkixQJAsNcGV1jBVDvwN+b7gVsYe2frkwggGweIOgKOfC3lZ0jfxreEk/VujvuWXL+WTfei69Gn83d+kCyqbx7Vkerd+0waVRZt/nOHacIV/VCm93JW0Mhku3izmhKyFyS8f/BgDaVpu5YlT1Qzm+MszDp1beLmg3gmDuJWI/nKpcW1/xpaUN71CG6psTKZ1Qdv4HaAe+1hmztntfAZfimoHPT0DWo1ZOAQbZJREgylqCMujoppsncnJnX0ArtkQrw=
  user: PunKeel
  file: ScreamShot.app.zip
  skip_cleanup: true
  on:
    repo: ScreamShot/ScreamShot
