osx_image: xcode6.4
language: objective-c
sudo: false

script: xctool -scheme ScreamShot build

before_deploy:
- mkdir ScreamShot.app/
- cp -R $HOME/Library/Developer/Xcode/DerivedData/*/Build/Products/Debug/ScreamShot.app/ ScreamShot.app/
- zip -r ScreamShot.app.zip ./ScreamShot.app/

deploy:
  provider: releases
  api_key:
    secure: djdRLFhr1Txk0rrE5xUK2nYTbKBvA+p5nadRXCKygxo8lHnNNuGYFGYN1/wIMHdkTkl7uq76Ve2ytIp28Mgk+zYnQQ2h/a8qHjT6zvrzl6+jBNeyaQElNZ/Cf/qCqttidCI5FOaDQghqlE2Da7ERMwOvV901BUHof3DJWA88y7k=
  file: ScreamShot.app.zip
  skip_cleanup: true
  on:
    repo: ScreamShot/ScreamShot
    tags: true